spring:
  application:
    name: lms-main-service

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 8095